In [2]:
  import nltk
  nltk.download('punkt')
  nltk.download('stopwords')
  from nltk.corpus import wordnet as wn
  import sklearn
  import os
  import re
  import pandas as pd
  import math
  import collections as cl
  import scipy as sp
  import numpy as np


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [3]:
from nltk.corpus.reader import wordnet
# Uploading the file
my_file = open("input_script.txt", "rt") # open lorem.txt for reading text
contents = my_file.read()         # read the entire file to string


#Cleaning the Text

# Below the code for removal of meta-deta
import re 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer  # For Steming the word
from nltk.stem import WordNetLemmatizer # It's an Word Limitizer

# Now Create Objects for cleaning Purposes

ps = PorterStemmer()
wordNet  =WordNetLemmatizer()
sentences = nltk.sent_tokenize(contents)
corpus = []
for i in range(len(sentences)):
  review = re.sub('[^a-zA-Z]', ' ', sentences[i])
  review = review.lower()
  review = review.split()
  review = [word for word in review if word not in stopwords.words('english')]
  #review = [wordnet.lemmatize(word) for word in review if not word in set (stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)
  review



In [4]:
#Creating the Bag of Words
#Count Vectorization

from sklearn.feature_extraction.text import CountVectorizer
cv  = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
X

array([[1, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [5]:
# N-Grams, Implementation of Bi Grams

from sklearn.feature_extraction.text import CountVectorizer
cv  = CountVectorizer(ngram_range = (2,2))
corpus = ["This is a first sentence",
          "This is an another sentence",
          "that the third sentence"]

X = cv.fit_transform(corpus)
print(X.shape)
print(X.toarray())

df = pd.DataFrame(X.toarray(), columns = cv.get_feature_names())
print(df)

(3, 9)
[[0 0 1 0 1 0 0 0 1]
 [1 1 0 1 0 0 0 0 1]
 [0 0 0 0 0 1 1 1 0]]
   an another  another sentence  ...  third sentence  this is
0           0                 0  ...               0        1
1           1                 1  ...               0        1
2           0                 0  ...               1        0

[3 rows x 9 columns]
